In [6]:
# What is numpy 
----------------------------
1. Numpy( Numerical python) is a python library for numerical computing.
2. It provides fast and efficient ways to work with arrays and matrices, and perform mathematical
   operations on them.
       
Note-
1. Python lists can store numbers, but they are slow for heavy calculations.
2. NumPy arrays are faster, more memory-efficient, and come with lots of built-in functions.


Key features
-------------------------------
1. N- dimensional arrays – Can store data in 1D, 2D, 3D, etc.
2. Fast mathematical operations – Vectorized operations are much faster than loops.
3. Linear algebra support – Matrix multiplication, determinants, eigenvalues.
4. Random number generations – Useful for simulations and probabilistic models.
5. Integration with other libraries – Pandas, Scikit-learn, TensorFlow, etc., all use NumPy arrays internally.


Why is NumPy Important in Data Science & Analytics?
------------------------------------------------------------------------

1. Efficiency & Speed – Large datasets can be processed much faster than Python lists.
2. Foundation for other libraries – Libraries like Pandas, Scikit-learn, Matplotlib, TensorFlow are built 
   on top of NumPy.
3. Supports Vectorization – Perform operations on entire arrays without using loops, which is crucial for 
   big data.
4. Mathematical & Statistical Operations – Mean, median, standard deviation, matrix operations, dot product, 
   linear algebra.
5. Data Manipulation – Reshaping arrays, slicing, indexing, and broadcasting make data handling easy.

In [65]:
# version check 
import numpy as np
print(np.__version__)

2.1.3


In [16]:
# creating arrays and matrix

import numpy as np
arr=np.array([1,2,3,4,5])
print("The array is",arr)

import numpy as np
print("The matrix is")
matrix=np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)

The array is [1 2 3 4 5]
The matrix is
[[1 2 3 4]
 [5 6 7 8]]


In [39]:
# Array initialization
# ----------------------------------

#zeros array
import numpy as np
print("The zeros matrix are")
zeros=np.zeros([3,4])
print(zeros)

#ones array
import numpy as np
print("The ones matrix are")
ones=np.ones([3,4])
print(ones)

# full array
print("The full matrix ")
full=np.full([3,4],7)
print(full)

#identity matrix
print("The identity matrix is")
identity=np.identity(4)                   # we can also use eye instead of identity
print(identity)

#random matrix
print("The random matrix is")
random=np.random.rand(2,2)
print(random)

#random integer matrix
print("The randint matrix is")
randint=np.random.randint(1,9,[3,4])
print(randint)

The zeros matrix are
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
The ones matrix are
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
The full matrix 
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
The identity matrix is
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
The random matrix is
[[0.19952854 0.08747682]
 [0.68957058 0.36027544]]
The randint matrix is
[[1 5 8 5]
 [5 8 7 2]
 [6 8 7 8]]


In [43]:
# array properties

print("The matrix is - ")
arr = np.array([[1,2,3,4],[4,5,6,7]])
print(arr)
print("The shape of the amatrix is",arr.shape)   
print("The dimensions of the matrix is",arr.ndim)    # 2 (dimensions)
print("The size of the matrix is",arr.size)          # 8 (total elements)
print("The data types of the matrix is",arr.dtype)   # int64 (depends on system)


The matrix is - 
[[1 2 3 4]
 [4 5 6 7]]
The shape of the amatrix is (2, 4)
The dimensions of the matrix is 2
The size of the matrix is 8
The data types of the matrix is int64


In [45]:
# Indexing and slicing

import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])       
print(arr[-1])      
print(arr[1:4])     
print(arr[:3])      
print(arr[::2])           # leave the element by 2 place    
print(arr[::-1])          # Reverse indexing

10
50
[20 30 40]
[10 20 30]
[10 30 50]
[50 40 30 20 10]


In [47]:
# for 2 d arrays
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix[0, 1])    # element at row 0, col 1 → 2
print(matrix[:, 2])    # all rows, col 1 → [2 5 8]
print(matrix[1, :])    # row 1 → [4 5 6]
print(matrix[0:2, 1:3]) # rows 0-1, cols 1-2 → [[2 3],[5 6]]


2
[3 6 9]
[4 5 6]
[[2 3]
 [5 6]]


In [49]:
# mathematical operations 
print("The result is")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]
print(a * b)   # [ 4 10 18]
print(a ** 2)  # [1 4 9]

# Scalar operations
print(a + 10)  # [11 12 13]


The result is
[5 7 9]
[ 4 10 18]
[1 4 9]
[11 12 13]


In [50]:
#matrix operatons

print("The result is")
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.dot(A, B))      # Matrix multiplication
print(A @ B)             # Same as dot
print(np.transpose(A))   # Transpose


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [53]:
# Useful function

print("The result is")
arr = np.array([10, 20, 30, 40, 50])

print(np.mean(arr))   # 30.0
print(np.median(arr)) # 30.0
print(np.std(arr))    # Standard deviation
print(np.min(arr))    # 10
print(np.max(arr))    # 50
print(np.sum(arr))    # 150


The result is
30.0
30.0
14.142135623730951
10
50
150
<class 'numpy.ndarray'>


In [54]:
# random module
np.random.seed(42)  # reproducibility

print(np.random.rand(3))           # 3 random floats
print(np.random.randn(3))          # normal distribution
print(np.random.randint(1, 10, 5)) # 5 random ints 1–9


[0.37454012 0.95071431 0.73199394]
[-1.11188012  0.31890218  0.27904129]
[8 3 6 5 2]


In [58]:
# Linear algebra

A = np.array([[1,2],[3,4]])
print("The matrix is",A)

det = np.linalg.det(A)
print(det)                  # Determinant

inv = np.linalg.inv(A)      # Inverse
print(inv)

eigvals, eigvecs = np.linalg.eig(A) # Eigenvalues, Eigenvectors
print(eigvals, eigvecs)


The matrix is [[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [63]:
# Reshaping and flattering

arr = np.arange(1, 7)   # [1 2 3 4 5 6]
print(arr)

reshaped = arr.reshape(2,3)
print(reshaped)

flattened = reshaped.flatten()
print(flattened)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [1]:
# Project-1 ----Monte carlo pi estimation using numpy and python 
---------------------------------------------------------
# 1. Basically this project shows us how we can find the value of pi.
# 2. Just take one square which contains 10000 points inside it.
# 3. Now make an circle in it from its one corner and it almost contains 7850 points.
# 4. This projects shows probability, simulation and Numpy vectorization.
# 5. In this we learn - Random numbers with NumPy, Boolean arrays and sum, Vectorized operations (no loops!)

import numpy as np
n_points=100000                          # take points

x=np.random.rand(n_points)               # Generate random x and y coordinates between 0 and 1
y=np.random.rand(n_points)

inside_circle=(x**2+y**2)<=1             # Check if points are inside the unit circle

count_sum=np.sum(inside_circle)          # count the points inside the circle

pi_estimate=4*(count_sum / n_points)     # now find the pi estimation.
print("The point estimation is",pi_estimate)

The point estimation is 3.14928


In [38]:
# project-2 
# Dice roll probabily estimation 
# In this we check  the probability of the sum of 2 dices (5,6,8,etc) at one time among 10000 chances.

import numpy as np
n_dice=10000

dice1=np.random.randint(1,7,size=n_dice)             # Simulate two dice rolls
dice2=np.random.randint(1,7,size=n_dice)

sum=dice1+dice2                                      # sum 

values,counts= np.unique(sum,return_counts=True)     # Count frequency of each sum (2 to 12)  

probability=(counts/n_dice)

for val, prob in zip(values,probabilities):          #
    print(f"Sum {val}: Probability - {prob}")

Sum 2: Probability - 0.02833
Sum 3: Probability - 0.05474
Sum 4: Probability - 0.08272
Sum 5: Probability - 0.11186
Sum 6: Probability - 0.13878
Sum 7: Probability - 0.1672
Sum 8: Probability - 0.13877
Sum 9: Probability - 0.11166
Sum 10: Probability - 0.0825
Sum 11: Probability - 0.05579
Sum 12: Probability - 0.02765
